# Generated by Django 4.0.4 on 2022-05-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('empID', models.CharField(max_length=5, null=True)),
                ('empEmail', models.EmailField(max_length=30, null=True)),
                ('profilePicture', models.ImageField(blank=True, default='profile/pngegg.png', null=True, upload_to='uploads')),
                ('address', models.CharField(max_length=30, null=True)),
                ('phoneNum', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('maritalStatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('Sep', 'Separated')], max_length=10, null=True)),
                ('availableVacation', models.IntegerField(null=True)),
                ('approvedVacation', models.IntegerField(null=True)),
                ('salaryVacation', models.IntegerField(null=True)),
                ('birthDate', models.DateField()),
            ],
        ),
    ]
