# Generated by Django 4.0.4 on 2022-05-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.CharField(default='submitted', max_length=15, null=True),
        ),
    ]
